"""
Persona synthesizer - Step 5c of persona creation pipeline.

For each enriched viewpoint, makes one LLM call to produce `role_desc` and `background`, then map onto GeneratedPersona.
"""
import logging
from typing import List

from configs.rag_config import SYNTHESIS_MAX_RETRIES
from rag._llm import build_llm, call_llm, parse_json_object
from rag.state import GeneratedPersona, Viewpoint

logger = logging.getLogger(__name__)

_LITHUANIAN_NAMES = [
    "Tomas", "Marta", "Andrius", "Rūta", "Lukas",
    "Eglė", "Mantas", "Kristina", "Darius", "Lina",
    "Paulius", "Indrė", "Arnas", "Jovita", "Žygimantas",
]

_SYSTEM_MESSAGE = """You are building a debate simulation persona.
Given a stakeholder's name (could be an individual or organisation), stance, arguments, and optional background \
context, produce a realistic human representative persona.

The persona's first name has already been assigned - do NOT include a name field.

Output ONLY a JSON object with exactly these keys:
- "role_desc": 1-2 sentences written in first person. The format must follow this \
pattern exactly: "I am a representative of [org name], [one factual clause about \
the organisation's mandate or core interest in this domain]. [One sentence stating \
the persona's directional stance on the topic and the primary reason for it.]" \
Do NOT invent a job title or describe a fictional career. The person is always \
"a representative of [org]". Keep the organisational description grounded in the \
enrichment context if provided, otherwise use the organisation name and type. \
Example: "I am a representative of LRT, Lithuania's statutory public broadcaster \
with a mandate to provide trusted public information. I believe platforms must be \
held to the same editorial accountability standards as traditional media, because \
inconsistent rules create an uneven playing field."
- "background": 1-2 sentences of institutional context drawn from the enrichment \
text below. If the enrichment text is empty, write a brief factual description \
of the organisation based on its name and type alone.

No markdown fences. No explanation. Output only the JSON object."""


def _build_user_message(topic: str, viewpoint: Viewpoint) -> str:
    """Build the user message for the synthesis LLM call."""
    source_name = viewpoint.get("source_name", "")
    source_type = viewpoint.get("source_type", "")
    stance = viewpoint.get("stance", "")
    key_arguments = viewpoint.get("key_arguments", [])
    enrichment_raw = viewpoint.get("_enrichment_raw", "")

    arguments_block = "\n".join(f"- {arg}" for arg in key_arguments)

    return (
        f"Debate topic: {topic}\n\n"
        f"Organisation: {source_name}\n"
        f"Organisation type: {source_type}\n"
        f"Stance on topic: {stance}\n"
        f"Key arguments:\n{arguments_block}\n\n"
        f"Enrichment context (may be empty):\n{enrichment_raw}"
    )


def synthesize_personas(topic: str, viewpoints: List[Viewpoint]) -> List[GeneratedPersona]:
    """
    Synthesize a GeneratedPersona for each enriched viewpoint via one LLM call each.

    Names are assigned from a static Lithuanian name list, role_desc and background are generated by the LLM based on the viewpoint's stance, arguments, and enrichment context.

    Args:
        topic: The debate topic string.
        viewpoints: Enriched viewpoints from background_fetcher (must have `_enrichment_raw`).

    Returns:
        List of fully-populated GeneratedPersona dicts, one per viewpoint.
    """
    llm = build_llm()
    personas: List[GeneratedPersona] = []

    for i, vp in enumerate(viewpoints):
        name = _LITHUANIAN_NAMES[i % len(_LITHUANIAN_NAMES)]
        source_name = vp.get("source_name", "")
        user_message = _build_user_message(topic, vp)

        parsed = None
        last_response = ""

        # attempt to parse the LLM response, with retries on failure up to SYNTHESIS_MAX_RETRIES
        for attempt in range(1, SYNTHESIS_MAX_RETRIES + 1):
            try:
                last_response = call_llm(llm, _SYSTEM_MESSAGE, user_message)
                data = parse_json_object(last_response)
                if "role_desc" not in data or "background" not in data:
                    raise KeyError(f"Missing required keys in response: {list(data.keys())}")
                parsed = data
                break
            except (json.JSONDecodeError, KeyError) as exc:
                logger.warning(
                    "[persona_synthesis] attempt %d/%d failed for '%s': %s\nRaw response: %s",
                    attempt, SYNTHESIS_MAX_RETRIES, source_name, exc, last_response,
                )

        # if parsing ultimately fails, raise an error to avoid silently producing incomplete personas
        if parsed is None:
            raise RuntimeError(
                f"[persona_synthesis] failed to parse LLM response for '{source_name}' "
                f"after {SYNTHESIS_MAX_RETRIES} attempts. Last raw response: {last_response!r}"
            )

        persona = GeneratedPersona(
            name=name,
            affiliation=source_name,
            role_desc=parsed["role_desc"],
            keypoints=vp.get("key_arguments", []),
            background=parsed["background"],
            stance=vp.get("stance", ""),
            sources=vp.get("sources", []),
        )
        logger.info(
            "[persona_synthesis] synthesized persona '%s' for '%s' [%s]",
            name, source_name, vp.get("stance", ""),
        )
        personas.append(persona)

    return personas
